(function(){
  const triggers=[...document.querySelectorAll('[data-global-archives]')];
  if(!triggers.length)return;
  const root=document.createElement('div');
  root.className='global-archive-backdrop';
  root.setAttribute('aria-hidden','true');
  root.innerHTML='<section class="global-archive-sheet" role="dialog" aria-modal="true" aria-label="档案管理"><header class="global-archive-head"><div><p class="eyebrow">ARCHIVE MANAGER</p><h2>档案管理</h2></div><button class="global-archive-close" aria-label="关闭">×</button></header><button class="global-archive-add" data-add>＋ 添加新档案</button><div class="global-archive-list"></div></section>';
  document.body.appendChild(root);
  const list=root.querySelector('.global-archive-list');
  const archives=()=>JSON.parse(localStorage.getItem('qingshiji-archives')||'[]');
  const selected=()=>localStorage.getItem('qingshiji-selected')||'';
  const storage=window.QingshiArchiveStorage||{async load(){try{const r=await fetch('./api/archives',{cache:'no-store'}),remote=r.ok?await r.json():[];const map=new Map();[...remote,...archives()].forEach(x=>x?.id&&map.set(x.id,x));const items=[...map.values()];localStorage.setItem('qingshiji-archives',JSON.stringify(items));return items}catch{return archives()}},async save(items){try{await fetch('./api/archives',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(items)})}catch{}return items}};
  const hex=g=>g==='男'?'<span class="global-hexagram qian" title="男性 · 乾三连"><i></i><i></i><i></i></span>':'<span class="global-hexagram kun" title="女性 · 坤六断"><i></i><i></i><i></i></span>';
  function render(){const items=archives(),sid=selected();list.innerHTML=items.length?items.map(x=>`<article class="global-archive-item ${x.id===sid?'selected':''}"><div class="global-archive-main"><div class="global-archive-avatar">${x.name.slice(0,1)}</div><div class="global-archive-copy"><b class="global-archive-name">${x.name}${hex(x.gender)}${x.id===sid?' · 当前':''}</b><p>${x.gender==='男'?'乾造':'坤造'} · ${x.location||''} · ${(x.solar||'').replace('T',' ')}</p></div></div><div class="global-archive-actions"><button data-select="${x.id}">选择</button><button data-edit="${x.id}">修改</button><button class="danger" data-delete="${x.id}">删除</button></div></article>`).join(''):'<div class="global-archive-empty">暂无档案<br><small>点击上方按钮添加第一份档案</small></div>'}
  function open(){render();root.classList.add('show');root.setAttribute('aria-hidden','false')}
  function close(){root.classList.remove('show');root.setAttribute('aria-hidden','true')}
  triggers.forEach(el=>el.addEventListener('click',e=>{e.preventDefault();open()}));
  root.querySelector('.global-archive-close').onclick=close;
  function openEditor(query){close();document.querySelector('.global-editor-shell')?.remove();const params=new URLSearchParams(query),standalone=params.get('target')==='hepan'||params.get('standalone')==='1';const shell=document.createElement('div');shell.className='global-editor-shell';shell.dataset.editorFlow=standalone?'standalone':'archive';shell.innerHTML='<div class="global-editor-loading">正在打开档案信息录入…</div><button class="global-editor-close" type="button" aria-label="关闭档案录入">×</button>';const frame=document.createElement('iframe');frame.className='global-bazi-editor';frame.title='档案信息录入';frame.scrolling='no';frame.setAttribute('allowtransparency','true');frame.src=`./bazi.html?embedded=1&${params.toString()}`;frame.addEventListener('load',()=>{shell.classList.add('loaded');try{const updateSize=()=>{const doc=frame.contentDocument;if(!doc)return;const height=Math.max(doc.documentElement.scrollHeight,doc.body?.scrollHeight||0);frame.style.height=`${Math.min(height,window.innerHeight-48)}px`};updateSize();new ResizeObserver(updateSize).observe(frame.contentDocument.body);window.addEventListener('resize',updateSize,{passive:true})}catch{}});shell.appendChild(frame);document.body.appendChild(shell);shell.querySelector('.global-editor-close').onclick=()=>{shell.remove();if(!standalone)open()}}
  window.QingshiArchiveManager={open,close,openEditor};
  root.addEventListener('click',e=>{if(e.target===root)close();const add=e.target.closest('[data-add]');if(add)openEditor('new=1');const edit=e.target.closest('[data-edit]');if(edit)openEditor(`edit=${encodeURIComponent(edit.dataset.edit)}`);const choose=e.target.closest('[data-select]');if(choose){localStorage.setItem('qingshiji-selected',choose.dataset.select);render();window.dispatchEvent(new CustomEvent('qingshiji-archive-selected',{detail:{id:choose.dataset.select}}))}const del=e.target.closest('[data-delete]');if(del&&confirm('确定删除这个档案吗？')){const next=archives().filter(x=>x.id!==del.dataset.delete);localStorage.setItem('qingshiji-archives',JSON.stringify(next));storage.save(next);if(selected()===del.dataset.delete)localStorage.removeItem('qingshiji-selected');render()}});
  window.addEventListener('message',e=>{if(e.origin!==location.origin||e.data!=='qingshiji-close-editor')return;const shell=document.querySelector('.global-editor-shell'),standalone=shell?.dataset.editorFlow==='standalone';shell?.remove();if(!standalone)open()});
  window.addEventListener('storage',render);
  storage.load().then(()=>{render();window.dispatchEvent(new CustomEvent('qingshiji-archives-loaded'))});
})();
